# Generated by Django 4.2.2 on 2023-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('create_date', models.DateField()),
                ('todo_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
