# Generated by Django 4.2.2 on 2023-06-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
