# Generated by Django 4.2.2 on 2023-06-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
